### ISSUE TITLE
VMWare image not working

### ISSUE THREAD

**Issue by drejfus** [fpsw/Servo#27]
# su servo
    $ . /opt/servo/env/bin/activate
    $ cd /opt/servo/app
    $ git pull origin master
    $ ./install.py

on freeBSD VM from yours page,

Errors, cannot execute install.py witchout error...

**Comment by filipp** [comment]
Thanks for the feedback, I'll look into it. Probably time to update whole image since FreeBSD 11 is out as well...

**Comment by drejfus** [comment]
Thanks for the quick response, very eager to test the solution. Waiting for the update :)

**Comment by valberbox** [comment]
reading given errors, I added some command to get pre-configured vmware image working:
``

    # su servo
    $ . /opt/servo/env/bin/activate
    $ cd /opt/servo/app
    $ git pull origin master
    $ pip install -U -r requirements.pip
    $ pip install html2text
    $ pip install chardet
    $ ./install.py
``
hope find this useful

**Comment by filipp** [comment]
@valberbox so it's working for you? Thanks for the tips. I'm actually working on an updated version with FreeBSD 11. Should really just build a script that takes any stock FreeBSD install and installs the necessary components... :)

**Comment by valberbox** [comment]
Hi filipp,
I confirm it's working. after adding those three lines install.py runs without errors.

**Comment by filipp** [comment]
Awesome, good to know! :)
