### ISSUE TITLE
Error installing vmware image.

### ISSUE THREAD

**Issue by cagj1976** [fpsw/Servo#32]
Tried the information on README.
On step ./install.py got error on printscreen
<img width="618" alt="Screen Shot 2020-10-23 at 16 10 08" src="https://user-images.githubusercontent.com/20858140/97022213-c19db200-154b-11eb-801f-b8f37461809d.png">
tried installing following instructions from VMWare image not working #27
<img width="618" alt="Screen Shot 2020-10-23 at 16 10 36" src="https://user-images.githubusercontent.com/20858140/97022362-ef82f680-154b-11eb-8a55-2ffea952d215.png">
<img width="618" alt="Screen Shot 2020-10-23 at 16 10 48" src="https://user-images.githubusercontent.com/20858140/97022449-088ba780-154c-11eb-8e66-c0b5464be4b7.png">
<img width="1752" alt="Screen Shot 2020-10-23 at 16 24 18" src="https://user-images.githubusercontent.com/20858140/97022599-38d34600-154c-11eb-947c-4bf11fb2d6b2.png">
<img width="618" alt="Screen Shot 2020-10-23 at 16 12 28" src="https://user-images.githubusercontent.com/20858140/97022639-45579e80-154c-11eb-87c0-185d9a837d8f.png">

Any tips on how to gett it working?

Thank you for your time

**Comment by TomBoehm** [comment]
For me it worked with:

in requirements.pip: (found via try & error ... not the ideal solution)
```
Django==1.11.29
tabulate<0.7.9
django-mptt==0.8.6
pyexcel==0.5.15
pyexcel-io==0.5.20
django-excel
django-countries==5.5
django-bootstrap3==8.2.2
djangorestframework<3.10
babel
markdown==2.6.11
python-memcached
psycopg2-binary
Pillow< 2.0.0
reportlab
pytz
phonenumbers
python-dateutil
pyBarcode
celery<3.2
chardet
html2text==2019.8.11
python-magic
pyexcel-xls
pyexcel-xlsx
pyexcel_text
gsxws
-e git+git://github.com/filipp/django-wkhtmltopdf.git#egg=django-wkhtmltopdf
```

```
su servo
$ . /opt/servo/env/bin/activate
$ cd /opt/servo/app
$ git pull origin master
$ pip install -U -r requirements.pip
$ export DJANGO_SETTINGS_MODULE="settings"
$ ./install.py
```

and in /usr/local/etc/nginx/servo.conf: change all `/opt/servo/app/` to `/opt/servo/app/servo/`

**Comment by filipp** [comment]
Thanks for your feedback! Containers seem to be the modern way of doing this so I will look into creating one for Servo.
